class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

class AuthSystem:
    def __init__(self):
        self.users = {}

    def register(self, username, password):
        if username in self.users:
            return False
        self.users[username] = User(username, password)
        return True

    def login(self, username, password):
        if username not in self.users:
            return False
        if self.users[username].password == password:
            return True
        return False

    def change_password(self, username, old_password, new_password):
        if username not in self.users:
            return False
        if self.users[username].password != old_password:
            return False
        self.users[username].password = new_password
        return True

    def delete_account(self, username, password):
        if username not in self.users:
            return False
        if self.users[username].password != password:
            return False
        del self.users[username]
        return True

auth_system = AuthSystem()

while True:
    print("1. Ro'yxatdan o'tish")
    print("2. Kirish")
    print("3. Parolni o'zgartirish")
    print("4. Hisobni o'chirish")
    print("5. Chiqish")
    print("6. Hisoblar ro'yxati")
    print("7. Chiqish")
    print("8. Chiqish")
    print("9. Chiqish")
    print("10. Chiqish")
    print("11. Chiqish")
    print("12. Chiqish")
    print("13. Chiqish")
    print("14. Chiqish")
    print("15. Chiqish")
    print("16. Chiqish")
    print("17. Chiqish")
    print("18. Chiqish")
    print("19. Chiqish")
    print("20. Chiqish")
    print("21. Chiqish")
    print("22. Chiqish")
    print("23. Chiqish")
    print("24. Chiqish")
    print("25. Chiqish")
    print("26. Chiqish")
    print("27. Chiqish")
    print("28. Chiqish")
    print("29. Chiqish")
    print("30. Chiqish")
    print("31. Chiqish")
    print("32. Chiqish")
    print("33. Chiqish")
    print("34. Chiqish")
    print("35. Chiqish")
    print("36. Chiqish")
    print("37. Chiqish")
    print("38. Chiqish")
    print("39. Chiqish")
    print("40. Chiqish")
    print("41. Chiqish")
    print("42. Chiqish")
    print("43. Chiqish")
    print("44. Chiqish")
    print("45. Chiqish")
    print("46. Chiqish")
    print("47. Chiqish")
    print("48. Chiqish")
    print("49. Chiqish")
    print("50. Chiqish")
    print("51. Chiqish")
    print("52. Chiqish")
    print("53. Chiqish")
    print("54. Chiqish")
    print("55. Chiqish")
    print("56. Chiqish")
    print("57. Chiqish")
    print("58. Chiqish")
    print("59. Chiqish")
    print("60. Chiqish")
    print("61. Chiqish")
    print("62. Chiqish")
    print("63. Chiqish")
    print("64. Chiqish")
    print("65. Chiqish")
    print("66. Chiqish")
    print("67. Chiqish")
    print("68. Chiqish")
    print("69. Chiqish")
    print("70. Chiqish")
    print("71. Chiqish")
    print("72. Chiqish")
    print("73. Chiqish")
    print("74. Chiqish")
    print("75. Chiqish")
    print("76. Chiqish")
    print("77. Chiqish")
    print("78. Chiqish")
    print("79. Chiqish")
    print("80. Chiqish")
    print("81. Chiqish")
    print("82. Chiqish")
    print("83. Chiqish")
    print("84. Chiqish")
    print("85. Chiqish")
    print("86. Chiqish")
    print("87. Chiqish")
    print("88. Chiqish")
    print("89. Chiqish")
    print("90. Chiqish")
    print("91. Chiqish")
    print("92. Chiqish")
    print("93. Chiqish")
    print("94. Chiqish")
    print("95. Chiqish")
    print("96. Chiqish")
    print("97. Chiqish")
    print("98. Chiqish")
    print("99. Chiqish")
    print("100. Chiqish")
    print("101. Chiqish")
    print("102. Chiqish")
    print("103. Chiqish")
    print("104. Chiqish")
    print("105. Chiqish")
    print("106. Chiqish")
    print("107. Chiqish")
    print("108. Chiqish")
    print("109. Chiqish")
    print("110. Chiqish")
    print("111. Chiqish")
    print("112. Chiqish")
    print("113. Chiqish")
    print("114. Chiqish")
    print("115. Chiqish")
    print("116. Chiqish")
    print("117. Chiqish")
    print("118. Chiqish")
    print("119. Chiqish")
    print("120. Chiqish")
    print("121. Chiqish")
    print("122. Chiqish")
    print("123. Chiqish")
    print("124. Chiqish")
    print("125. Chiqish")
    print("126. Chiqish")
    print("127. Chiqish")
    print("128. Chiqish")
    print("129. Chiqish")
    print("130. Chiqish")
    print("131. Chiqish")
    print("132. Chiqish")
    print("133. Chiqish")
    print("134. Chiqish")
    print("135. Chiqish")
    print("136. Chiqish")
    print("137. Chiqish")
    print("138. Chiqish")
    print("139. Chiqish")
    print("140. Chiqish")
    print("141. Chiqish")
    print("142. Chiqish")
    print("143. Chiqish")
    print("144. Chiqish")
    print("145. Chiqish")
    print("146. Chiqish")
    print("147. Chiqish")
    print("148. Chiqish")
    print("149. Chiqish")
    print("150. Chiqish")
    print("151. Chiqish")
    print("152. Chiqish")
    print("153. Chiqish")
    print("154. Chiqish")
    print("155. Chiqish")
    print("156. Chiqish")
    print("157. Chiqish")
    print("158. Chiqish")
    print("159. Chiqish")
    print("160. Chiqish")
    print("161. Chiqish")
    print("162. Chiqish")
    print("163. Chiqish")
    print("164. Chiqish")
    print("165. Chiqish")
    print("166. Chiqish")
    print("167. Chiqish")
    print("168. Chiqish")
    print("169. Chiqish")
    print("170. Chiqish")
    print("171. Chiqish")
    print("172. Chiqish")
    print("173. Chiqish")
    print("174. Chiqish")
    print("175. Chiqish")
    print("176. Chiqish")
    print("177. Chiqish")
    print("178. Chiqish")
    print("179. Chiqish")
    print("180. Chiqish")
    print("181. Chiqish")
    print("182. Chiqish")
    print("183. Chiqish")
    print("184. Chiqish")
    print("185. Chiqish")
    print("186. Chiqish")
    print("187. Chiqish")
    print("188. Chiqish")
    print("189. Chiqish")
    print("190. Chiqish")
    print("191. Chiqish")
    print("192. Chiqish")
    print("193. Chiqish")
    print("194. Chiqish")
    print("195. Chiqish")
    print("196. Chiqish")
    print("197. Chiqish")
    print("198. Chiqish")
    print("199. Chiqish")
    print("
